CELL_CLASS : dict = {"square blank": 'blank',
                     "square bombflagged": 'flagged',
                     "square bombflagged checked": 'flagged',
                     "square bombdeath": 'death',
                     "square open0": 0,
                     "square open1": 1,
                     "square open2": 2,
                     "square open3": 3,
                     "square open4": 4,
                     "square open5": 5,
                     "square open6": 6,
                     "square open7": 7,
                     "square open8": 8}